name: deploy

on:
  push:
    branch:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: npm install
    - name: Build
      run: npm run build
